# Generated by Django 4.2.7 on 2024-01-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_salon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
