# Generated by Django 4.2.7 on 2024-01-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
