# Generated by Django 4.2.7 on 2024-01-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_ordershistory_alter_worker_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='process.worker')),
            ],
        ),
    ]
