# Generated by Django 4.2.7 on 2024-01-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershistory',
            name='staff_login',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
